### ISSUE TITLE
Unclear as to what hardware this driver supports (IDFGH-13332)

### ISSUE THREAD

**Issue by 404ClickBait** [espressif/esp-win-usb-drivers#5]
I am trying to use the ESP-Prog programming board and wondering if this is the right driver vs some description on Espressif's site describes a process of installing D2xxx drivers from FTDI and then modifying the drivers using the Zadig tool

(sorry if this is not an appropriate place to pose this issue)

**Comment by jakub-kocka** [comment]
Hello @404ClickBait,

Yes, this is the right place to ask, and we apologize for any confusion. Drivers on Windows can indeed be tricky.

First of all, a useful tool for managing drivers (getting information about, installing, or deleting them) is [PnPUtil](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/pnputil).


Could you please let us know how you installed your ESP-IDF?

The easiest method is to use the [Windows IDF installer](https://dl.espressif.com/dl/esp-idf/). With this installer, you can choose to install the FTDI driver. However, on Windows, this driver might not work as expected, so after installation, you may need to manually switch or add the driver using a tool like Zadig. The drivers in this repository automate this process—you just need to download and install them.

For the ESP-PROG, the driver should work correctly. The right driver should be the [Espressif JTAG](https://github.com/espressif/esp-win-usb-drivers/releases/tag/ESP32-USB-JTAG_v6.1.7600.16386) driver, and it is installed when using the Windows IDF installer (installing it from the link should work as well). In `Device Manager`, it should appear as "JTAG," probably under the "Other devices" category.

I hope this helps.

**Comment by jakub-kocka** [comment]
Now, you can use the [ESP-PROG driver](https://github.com/espressif/esp-win-usb-drivers/releases/tag/ESP-PROG_v1.0.0.0) after installing the FTDI one.

We are closing this because of the added driver.

If anything won't work as expected, feel free to re-open this issue.
